name: Clang Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Autoformat
        id: format
        uses: SKIRT/auto-format@master
      - name: Autocommit
        if: steps.format.outputs.status == 'changed'
        run: |
          git config --global user.name 'auto-format'
          git config --global user.email 'auto-format@auto.format'
          git commit -am "Autoformat"
          git push
